/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RepairAddImport } from './routes/repair-add'
import { Route as RepairImport } from './routes/repair'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as PostsAddImport } from './routes/posts/add'

// Create/Update Routes

const RepairAddRoute = RepairAddImport.update({
  id: '/repair-add',
  path: '/repair-add',
  getParentRoute: () => rootRoute,
} as any)

const RepairRoute = RepairImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const PostsAddRoute = PostsAddImport.update({
  id: '/posts/add',
  path: '/posts/add',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairImport
      parentRoute: typeof rootRoute
    }
    '/repair-add': {
      id: '/repair-add'
      path: '/repair-add'
      fullPath: '/repair-add'
      preLoaderRoute: typeof RepairAddImport
      parentRoute: typeof rootRoute
    }
    '/posts/add': {
      id: '/posts/add'
      path: '/posts/add'
      fullPath: '/posts/add'
      preLoaderRoute: typeof PostsAddImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repair': typeof RepairRoute
  '/repair-add': typeof RepairAddRoute
  '/posts/add': typeof PostsAddRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repair': typeof RepairRoute
  '/repair-add': typeof RepairAddRoute
  '/posts/add': typeof PostsAddRoute
  '/posts': typeof PostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repair': typeof RepairRoute
  '/repair-add': typeof RepairAddRoute
  '/posts/add': typeof PostsAddRoute
  '/posts/': typeof PostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/repair'
    | '/repair-add'
    | '/posts/add'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/repair' | '/repair-add' | '/posts/add' | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/repair'
    | '/repair-add'
    | '/posts/add'
    | '/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RepairRoute: typeof RepairRoute
  RepairAddRoute: typeof RepairAddRoute
  PostsAddRoute: typeof PostsAddRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RepairRoute: RepairRoute,
  RepairAddRoute: RepairAddRoute,
  PostsAddRoute: PostsAddRoute,
  PostsIndexRoute: PostsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/repair",
        "/repair-add",
        "/posts/add",
        "/posts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/repair": {
      "filePath": "repair.tsx"
    },
    "/repair-add": {
      "filePath": "repair-add.tsx"
    },
    "/posts/add": {
      "filePath": "posts/add.tsx"
    },
    "/posts/": {
      "filePath": "posts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
